config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  post '/filter', to: 'search#filter'
  resources :organisateurs
  resources :evenements
  devise_for :users, controllers: {registrations: "registrations"}
  root 'home#index'

  post '/', to: 'home#newcomment'
  delete '/comment/:id_event/:id_comment', to: 'home#delcomment', as: "del_comment"

  get 'events/:id/show', to: 'home#show', as: 'event_show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organisateur.rb
class Organisateur < ApplicationRecord
    has_many :evenements
    has_one :status
    belongs_to :user
    accepts_nested_attributes_for :evenements
end

app/controllers/organisateurs_controller.rb
class OrganisateursController < ApplicationController
  before_action :set_organisateur, only: [:show, :edit, :update, :destroy]

  # GET /organisateurs
  # GET /organisateurs.json
  def index
    @organisateurs = Organisateur.all
    respond_to do |format|
      format.html
      format.json {render json: @organisateurs}
    end
  end

  # GET /organisateurs/1
  # GET /organisateurs/1.json
  def show
  end

  # GET /organisateurs/new
  def new
    @organisateur = Organisateur.new
    @statuses = Status.all
    if user_signed_in?
      @categories = Category.all
    else
      redirect_to new_user_session_path
    end
  end

  # GET /organisateurs/1/edit
  def edit
  end

  # POST /organisateurs
  # POST /organisateurs.json
  def create
    @organisateur = Organisateur.new(organisateur_params)
    @organisateur.status = Status.find(params[:status_id])
    @organisateur.user = current_user

    respond_to do |format|
      if @organisateur.save
        format.html { redirect_to new_evenement_path, notice: 'Organisateur was successfully created.' }
        format.json { render :show, status: :created, location: @organisateur }
        format.js
      else
        format.html { render :new }
        format.json { render json: @organisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisateurs/1
  # PATCH/PUT /organisateurs/1.json
  def update
    respond_to do |format|
      if @organisateur.update(organisateur_params)
        format.html { redirect_to @organisateur, notice: 'Organisateur was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisateur }
      else
        format.html { render :edit }
        format.json { render json: @organisateur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisateurs/1
  # DELETE /organisateurs/1.json
  def destroy
    @organisateur.destroy
    respond_to do |format|
      format.html { redirect_to organisateurs_url, notice: 'Organisateur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisateur
      @organisateur = Organisateur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisateur_params
      params.require(:organisateur).permit(:title, :about)
    end
end

app/helpers/organisateurs_helper.rb
module OrganisateursHelper
end

app/views/organisateurs/_form.html.erb
<%= form_with(model: organisateur, local: false, remote: true, html: {id: "org"}) do |form| %>
  <% if organisateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisateur.errors.count, "error") %> prohibited this organisateur from being saved:</h2>

      <ul>
      <% organisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nom_organisation %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field-select">
    <select class="form-control" name="status_id">
      <% @statuses.each do |s|%>
        <option value="<%= s.id %>"><%= s.title %></option>
      <%end%>
    </select>
  </div>

  <div class="actions">
    <button>Create</button>
  </div>
<% end %>

app/views/organisateurs/create.js.erb
$("#org").remove()
$("#no-org").css('display','block')
$.get("/organisateurs.json", function(data){
  let options_organisateur = ""
  for(let i = 0; i < data.length; i++){
    options_organisateur += '<option value="'+data[i].id+'">'+data[i].title+"</option>"
  } 
  $("#opt-org").html(options_organisateur)
  $("#opt-org").css('display','block')
  $(".field-select .nice-select").remove()
})

app/views/organisateurs/edit.html.erb
<h1>Editing Organisateur</h1>

<%= render 'form', organisateur: @organisateur %>

<%= link_to 'Show', @organisateur %> |
<%= link_to 'Back', organisateurs_path %>

app/views/organisateurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisateurs</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>A propos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisateurs.each do |organisateur| %>
      <tr>
        <td><%= organisateur.title %></td>
        <td><%= organisateur.about %></td>
        <td><%= link_to 'Show', organisateur %></td>
        <td><%= link_to 'Edit', edit_organisateur_path(organisateur) %></td>
        <td><%= link_to 'Destroy', organisateur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisateur', new_organisateur_path %>

app/views/organisateurs/new.html.erb
<%= render 'layouts/nav'%>
<!--================Breadcrumb Area =================-->
<section class="breadcrumb_area blog_banner_two">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle f_48">Mes evenements</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Acceuil</a></li>
                <li class="active">Mes evenements</li>
            </ol>
        </div>
    </div>
</section>
<!--================Breadcrumb Area =================-->
  
  <!--================Blog Categorie Area =================-->
  
  <!--================Blog Categorie Area =================-->
  
  <!--================Blog Area =================-->
  <section class="blog_area">
      <div class="container">
          <div class="row">
              <div class="col-lg-8">
                  <div class="blog_left_sidebar">
                  <h1 class="typo-list">Vous n'avez aucun evenement actif</h1>
                  <%= render 'form', organisateur: @organisateur %>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="blog_right_sidebar">
                      <aside class="single_sidebar_widget search_widget">
                          <div class="input-group">
                              <input type="text" class="form-control" placeholder="Search Posts">
                              <span class="input-group-btn">
                                  <button class="btn btn-default" type="button"><i class="lnr lnr-magnifier"></i></button>
                              </span>
                          </div><!-- /input-group -->
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget popular_post_widget">
                          <h3 class="widget_title">Popular Posts</h3>
                          <div class="media post_item">
                              <img src="image/blog/post1.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Space The Final Frontier</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post2.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>The Amazing Hubble</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post3.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Astronomy Or Astrology</h3></a>
                                  <p>03 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post4.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Asteroids telescope</h3></a>
                                  <p>01 Hours ago</p>
                              </div>
                          </div>
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget post_category_widget">
                          <h4 class="widget_title">Categories</h4>
                          <ul class="list_style cat-list">
                            <% @categories.each do |c| %>
                              <li>
                                  <a href="#" class="d-flex justify-content-between">
                                      <p><%= c.name.capitalize %></p>
                                      <p><%= Evenement.where(category_id: c.id).count %></p>
                                  </a>
                              </li>	
                            <%end%>  													
                          </ul>
                          <div class="br"></div>
                      </aside>
                      <aside class="single-sidebar-widget newsletter_widget">
                          <h4 class="widget_title">Newsletter</h4>
                          <p>
                          Here, I focus on a range of items and features that we use in life without
                          giving them a second thought.
                          </p>
                          <div class="form-group d-flex flex-row">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                                  </div>
                                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'">
                              </div>
                              <a href="#" class="bbtns">Subcribe</a>
                          </div>	
                          <p class="text-bottom">You can unsubscribe at any time</p>	
                          <div class="br"></div>							
                      </aside>
                      <aside class="single-sidebar-widget tag_cloud_widget">
                          <h4 class="widget_title">Tag Clouds</h4>
                          <ul class="list_style">
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Architecture</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Art</a></li>
                              <li><a href="#">Adventure</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Adventure</a></li>
                          </ul>
                      </aside>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--================Blog Area =================-->
<%= render 'layouts/footer'%>

app/views/organisateurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @organisateur.title %>
</p>

<p>
  <strong>A propos:</strong>
  <%= @organisateur.about %>
</p>

<%= link_to 'Edit', edit_organisateur_path(@organisateur) %> |
<%= link_to 'Back', organisateurs_path %>