config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  post '/filter', to: 'search#filter'
  resources :organisateurs
  resources :evenements
  devise_for :users, controllers: {registrations: "registrations"}
  root 'home#index'

  post '/', to: 'home#newcomment'
  delete '/comment/:id_event/:id_comment', to: 'home#delcomment', as: "del_comment"

  get 'events/:id/show', to: 'home#show', as: 'event_show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/evenement.rb
class Evenement < ApplicationRecord
  mount_uploader :picture, EventUploader

  belongs_to :category
  belongs_to :organisateur
  has_many :commentaires
  has_one :section
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :set_evenement, only: [:show, :edit, :update, :destroy]

  # GET /evenements
  # GET /evenements.json
  def index
    if user_signed_in?
      @categories = Category.all
      @organisateur = Organisateur.find_by(user_id: current_user.id)
      if @organisateur
        @events = Evenement.where(organisateur_id: @organisateur.id)
      else
        @events = []
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/1
  # GET /evenements/1.json
  def show
    if user_signed_in?
      @evenement = Evenement.find(params[:id])
      @comments = Commentaire.where(evenement_id: @evenement.id)
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/new
  def new
    @categories = Category.all
    if user_signed_in?
      @organisateurs = Organisateur.where(user_id: current_user.id)
      @statuses = Status.all
      @organisateur = Organisateur.new
      if @organisateurs != []
        @evenement = Evenement.new
      else
        # redirect_to new_organisateur_path
        @evenement = Evenement.new
        @organisateur = Organisateur.new
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/1/edit
  def edit
    if user_signed_in?
      @categories = Category.all
      @organisateurs = Organisateur.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  # POST /evenements
  # POST /evenements.json
  def create
    @categories = Category.all
    @organisateurs = Organisateur.where(user_id: current_user.id)

    @evenement = Evenement.new(evenement_params)
    cat = Category.find(params[:category_id])
    org = Organisateur.find(params[:organisateur_id])
    @evenement.category = cat
    @evenement.organisateur = org
    respond_to do |format|
      if @evenement.save
        format.html { redirect_to event_show_path(@evenement.id), notice: 'Evenement was successfully created.' }
        format.json { render :show, status: :created, location: @evenement }
      else
        format.html { render :new }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evenements/1
  # PATCH/PUT /evenements/1.json
  def update
    respond_to do |format|
      if @evenement.update(evenement_params)
        format.html { redirect_to @evenement, notice: 'Evenement was successfully updated.' }
        format.json { render :show, status: :ok, location: @evenement }
      else
        format.html { render :edit }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evenements/1
  # DELETE /evenements/1.json
  def destroy
    comment = Commentaire.where(evenement_id: params[:id])
    comment.each do |c|
      c.destroy
    end
    @evenement.destroy
    respond_to do |format|
      format.html { redirect_to evenements_url, notice: 'Evenement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evenement
      @evenement = Evenement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evenement_params
      params.require(:evenement).permit(:titre, :description, :date, :price, :picture, :lat, :lng)
    end
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/views/evenements/_form.html.erb
<%= form_with(model: evenement, local: true, :html => {id: "event",multipart: true}) do |form| %>
  <% if evenement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evenement.errors.count, "error") %> prohibited this evenement from being saved:</h2>

      <ul>
      <% evenement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Picture %>
    <%= form.file_field :picture%>
  </div>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <div class="input-group date" id="datetimepicker11">
      <%= form.label :date %>
      <%= form.text_field :date, class: "form-control" %>
      <span class="input-group-addon">
          <i class="fa fa-calendar" aria-hidden="true"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <select name="category_id">
      <% @categories.each do |cat|%>
        <option value="<%= cat.id %>"><%= cat.name %></option>
      <%end%>
    </select>
  </div>

  <div class="field">
    <select name="organisateur_id" id="opt-org">
      <% @organisateurs.each do |org|%>
        <option value="<%= org.id %>"><%= org.title %></option>
      <%end%>
    </select>
  </div>

  <!--map div-->
  <div id="map"  class="map"></div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :lat, id: "lat",readonly: "yes"  %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :lng, id: "lng", readonly: "yes" %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evenements/edit.html.erb
<h1>Editing Evenement</h1>

<%= render 'form', evenement: @evenement %>

<%= link_to 'Show', @evenement %> |
<%= link_to 'Back', evenements_path %>

app/views/evenements/index.html.erb
<%= render 'layouts/nav'%>
<!--================Breadcrumb Area =================-->
<section class="breadcrumb_area blog_banner_two">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle f_48">Mes evenements</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Acceuil</a></li>
                <li class="active">Mes evenements</li>
            </ol>
        </div>
    </div>
</section>
<!--================Breadcrumb Area =================-->
  
  <!--================Blog Categorie Area =================-->
  
  <!--================Blog Categorie Area =================-->
  
  <!--================Blog Area =================-->
  <section class="blog_area">
      <div class="container">
          <div class="row">
              <div class="col-lg-8">
                  <div class="blog_left_sidebar">
                  <% if @events != [] %>
                    <% @events.each do |e| %>
                      <article class="row blog_item">
                          <div class="col-md-3">
                              <div class="blog_info text-right">
                                  <div class="post_tag">
                                      <a href="#"><%= e.category.name.capitalize %></a>
                                  </div>
                                  <ul class="blog_meta list_style">
                                      <li><a href="#"><%= User.find(e.organisateur.user_id).name %><i class="lnr lnr-user"></i></a></li>
                                      <li><a href="#"><%= e.date.strftime("%d %b, %Y") %><i class="lnr lnr-calendar-full"></i></a></li>
                                      <li><a href="#">1.2M Views<i class="lnr lnr-eye"></i></a></li>
                                      <li><a href="#"><%= Commentaire.where(evenement_id: e.id).count %> Comments<i class="lnr lnr-bubble"></i></a></li>
                                  </ul>
                              </div>
                          </div>
                          <div class="col-md-9">
                              <div class="blog_post">
                                  <div style="
                                    background: url(<%= e.picture_url %>);
                                    background-size: cover;
                                    background-position: center center;
                                    width: 100%;
                                    height: 300px;
                                    ">
                                  </div>
                                  <div class="blog_details">
                                      <a href="#"><h2><%= e.titre %></h2></a>
                                      <p><%= e.description %></p>
                                      <a href="<%= event_show_path(e.id)%>" class="view_btn button_hover">Voir plus</a>
                                  </div>
                              </div>
                          </div>
                      </article>
                    <%end%>
                  <%else%>
                  <h1 class="typo-list">Vous n'avez aucun evenement actif</h1> 
                  <a href="<%= new_evenement_path %>" class="btn theme_btn button_hover">Creer un evenement</a>
                  <%end%>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="blog_right_sidebar">
                      <aside class="single_sidebar_widget search_widget">
                          <div class="input-group">
                              <input type="text" class="form-control" placeholder="Search Posts">
                              <span class="input-group-btn">
                                  <button class="btn btn-default" type="button"><i class="lnr lnr-magnifier"></i></button>
                              </span>
                          </div><!-- /input-group -->
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget popular_post_widget">
                          <h3 class="widget_title">Popular Posts</h3>
                          <div class="media post_item">
                              <img src="image/blog/post1.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Space The Final Frontier</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post2.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>The Amazing Hubble</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post3.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Astronomy Or Astrology</h3></a>
                                  <p>03 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post4.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Asteroids telescope</h3></a>
                                  <p>01 Hours ago</p>
                              </div>
                          </div>
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget post_category_widget">
                          <h4 class="widget_title">Categories</h4>
                          <ul class="list_style cat-list">
                            <% @categories.each do |c| %>
                              <li>
                                  <a href="#" class="d-flex justify-content-between">
                                      <p><%= c.name.capitalize %></p>
                                      <p><%= Evenement.where(category_id: c.id).count %></p>
                                  </a>
                              </li>	
                            <%end%>  													
                          </ul>
                          <div class="br"></div>
                      </aside>
                      <aside class="single-sidebar-widget newsletter_widget">
                          <h4 class="widget_title">Newsletter</h4>
                          <p>
                          Here, I focus on a range of items and features that we use in life without
                          giving them a second thought.
                          </p>
                          <div class="form-group d-flex flex-row">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                                  </div>
                                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'">
                              </div>
                              <a href="#" class="bbtns">Subcribe</a>
                          </div>	
                          <p class="text-bottom">You can unsubscribe at any time</p>	
                          <div class="br"></div>							
                      </aside>
                      <aside class="single-sidebar-widget tag_cloud_widget">
                          <h4 class="widget_title">Tag Clouds</h4>
                          <ul class="list_style">
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Architecture</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Art</a></li>
                              <li><a href="#">Adventure</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Adventure</a></li>
                          </ul>
                      </aside>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--================Blog Area =================-->
<%= render 'layouts/footer'%>

app/views/evenements/new.html.erb
<%= render 'layouts/nav'%>
<!--================Breadcrumb Area =================-->
<section class="breadcrumb_area blog_banner_two">
    <div class="overlay bg-parallax" data-stellar-ratio="0.8" data-stellar-vertical-offset="0" data-background=""></div>
    <div class="container">
        <div class="page-cover text-center">
            <h2 class="page-cover-tittle f_48">Mes evenements</h2>
            <ol class="breadcrumb">
                <li><a href="<%= root_path %>">Acceuil</a></li>
                <li class="active">Mes evenements</li>
            </ol>
        </div>
    </div>
</section>
<!--================Breadcrumb Area =================-->
  
  <!--================Blog Categorie Area =================-->
  
  
  <!--================Blog Categorie Area =================-->
  
  <!--================Blog Area =================-->
  <section class="blog_area">
      <div class="container">
          <div class="row">
              <div class="col-lg-8">
                  <div class="blog_left_sidebar">
                  <h1 class="typo-list">Vous n'avez aucun evenement actif</h1>
                  <% if @organisateurs == [] %>
                    <%= render 'organisateurs/form', organisateur: @organisateur %>
                    <div id="no-org" style="display: none">
                    <%= render 'form', evenement: @evenement %>
                    </div>
                  <%else%>
                    <%= render 'form', evenement: @evenement %>
                  <%end%>
                  </div>
              </div>
              <div class="col-lg-4">
                  <div class="blog_right_sidebar">
                      <aside class="single_sidebar_widget search_widget">
                          <div class="input-group">
                              <input type="text" class="form-control" placeholder="Search Posts">
                              <span class="input-group-btn">
                                  <button class="btn btn-default" type="button"><i class="lnr lnr-magnifier"></i></button>
                              </span>
                          </div><!-- /input-group -->
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget popular_post_widget">
                          <h3 class="widget_title">Popular Posts</h3>
                          <div class="media post_item">
                              <img src="image/blog/post1.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Space The Final Frontier</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post2.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>The Amazing Hubble</h3></a>
                                  <p>02 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post3.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Astronomy Or Astrology</h3></a>
                                  <p>03 Hours ago</p>
                              </div>
                          </div>
                          <div class="media post_item">
                              <img src="image/blog/post4.jpg" alt="post">
                              <div class="media-body">
                                  <a href="blog-details.html"><h3>Asteroids telescope</h3></a>
                                  <p>01 Hours ago</p>
                              </div>
                          </div>
                          <div class="br"></div>
                      </aside>
                      <aside class="single_sidebar_widget post_category_widget">
                          <h4 class="widget_title">Categories</h4>
                          <ul class="list_style cat-list">
                            <% @categories.each do |c| %>
                              <li>
                                  <a href="#" class="d-flex justify-content-between">
                                      <p><%= c.name.capitalize %></p>
                                      <p><%= Evenement.where(category_id: c.id).count %></p>
                                  </a>
                              </li>	
                            <%end%>  													
                          </ul>
                          <div class="br"></div>
                      </aside>
                      <aside class="single-sidebar-widget newsletter_widget">
                          <h4 class="widget_title">Newsletter</h4>
                          <p>
                          Here, I focus on a range of items and features that we use in life without
                          giving them a second thought.
                          </p>
                          <div class="form-group d-flex flex-row">
                              <div class="input-group">
                                  <div class="input-group-prepend">
                                      <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                                  </div>
                                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'">
                              </div>
                              <a href="#" class="bbtns">Subcribe</a>
                          </div>	
                          <p class="text-bottom">You can unsubscribe at any time</p>	
                          <div class="br"></div>							
                      </aside>
                      <aside class="single-sidebar-widget tag_cloud_widget">
                          <h4 class="widget_title">Tag Clouds</h4>
                          <ul class="list_style">
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Architecture</a></li>
                              <li><a href="#">Fashion</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Technology</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Art</a></li>
                              <li><a href="#">Adventure</a></li>
                              <li><a href="#">Food</a></li>
                              <li><a href="#">Lifestyle</a></li>
                              <li><a href="#">Adventure</a></li>
                          </ul>
                      </aside>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--================Blog Area =================-->
<%= render 'layouts/footer'%>

app/views/evenements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @evenement.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @evenement.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @evenement.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @evenement.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @evenement.category.name %>
</p>

<p>
  <strong>organisateur:</strong>
  <%= @evenement.organisateur.title %>
</p>

<% @comments.each do |f| %>
  <ul>
    <form action="del" method="delete" >
      <input type="hidden" name="id_comment" value="<%= f.id %>"  >
      <li> <%= f.comment %> </li>
      <input  type="submit" name="Envoyer">
    </form>
  </ul>
<%end%>

<form action="/" method="post" >
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
    <input type="hidden" name="id_en_cours" value="<%= @evenement.id %>"  >
    Votre commentaire: <br>
    <textarea name="comment"
    rows="3" cols="50">
    </textarea> <br><br>
    <input  type="submit" name="Envoyer">

</form>

<%= image_tag @evenement.picture_url %>
<%= link_to "Deconnexion", evenement_path(@evenement.id), method: :delete %>

<% if current_user.id == @evenement.user_id %>
<%= link_to 'Edit', edit_evenement_path(@evenement) %> 
<%end%>
<%= link_to 'Back', evenements_path %>