config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  post '/filter', to: 'search#filter'
  resources :organisateurs
  resources :evenements
  devise_for :users, controllers: {registrations: "registrations"}
  root 'home#index'

  post '/', to: 'home#newcomment'
  delete '/comment/:id_event/:id_comment', to: 'home#delcomment', as: "del_comment"

  get 'events/:id/show', to: 'home#show', as: 'event_show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
  belongs_to :evenement
  belongs_to :user
end

app/models/evenement.rb
class Evenement < ApplicationRecord
  mount_uploader :picture, EventUploader

  belongs_to :category
  belongs_to :organisateur
  has_many :commentaires
  has_one :section
end

app/models/organisateur.rb
class Organisateur < ApplicationRecord
    has_many :evenements
    has_one :status
    belongs_to :user
    accepts_nested_attributes_for :evenements
end

app/models/section.rb
class Section < ApplicationRecord
  # has_many :user
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :organisateur
  has_many :commentaire
  # belongs_to :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_action :sanitize_devise_params, if: :devise_controller?

    def sanitize_devise_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :country, :city])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :country, :city])
    end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all
    render json: @categories
  end
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  before_action :set_evenement, only: [:show, :edit, :update, :destroy]

  # GET /evenements
  # GET /evenements.json
  def index
    if user_signed_in?
      @categories = Category.all
      @organisateur = Organisateur.find_by(user_id: current_user.id)
      if @organisateur
        @events = Evenement.where(organisateur_id: @organisateur.id)
      else
        @events = []
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/1
  # GET /evenements/1.json
  def show
    if user_signed_in?
      @evenement = Evenement.find(params[:id])
      @comments = Commentaire.where(evenement_id: @evenement.id)
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/new
  def new
    @categories = Category.all
    if user_signed_in?
      @organisateurs = Organisateur.where(user_id: current_user.id)
      @statuses = Status.all
      @organisateur = Organisateur.new
      if @organisateurs != []
        @evenement = Evenement.new
      else
        # redirect_to new_organisateur_path
        @evenement = Evenement.new
        @organisateur = Organisateur.new
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /evenements/1/edit
  def edit
    if user_signed_in?
      @categories = Category.all
      @organisateurs = Organisateur.where(user_id: current_user.id)
    else
      redirect_to new_user_session_path
    end
  end

  # POST /evenements
  # POST /evenements.json
  def create
    @categories = Category.all
    @organisateurs = Organisateur.where(user_id: current_user.id)

    @evenement = Evenement.new(evenement_params)
    cat = Category.find(params[:category_id])
    org = Organisateur.find(params[:organisateur_id])
    @evenement.category = cat
    @evenement.organisateur = org
    respond_to do |format|
      if @evenement.save
        format.html { redirect_to event_show_path(@evenement.id), notice: 'Evenement was successfully created.' }
        format.json { render :show, status: :created, location: @evenement }
      else
        format.html { render :new }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evenements/1
  # PATCH/PUT /evenements/1.json
  def update
    respond_to do |format|
      if @evenement.update(evenement_params)
        format.html { redirect_to @evenement, notice: 'Evenement was successfully updated.' }
        format.json { render :show, status: :ok, location: @evenement }
      else
        format.html { render :edit }
        format.json { render json: @evenement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evenements/1
  # DELETE /evenements/1.json
  def destroy
    comment = Commentaire.where(evenement_id: params[:id])
    comment.each do |c|
      c.destroy
    end
    @evenement.destroy
    respond_to do |format|
      format.html { redirect_to evenements_url, notice: 'Evenement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evenement
      @evenement = Evenement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evenement_params
      params.require(:evenement).permit(:titre, :description, :date, :price, :picture, :lat, :lng)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @events = Evenement.page(params[:page]).per(5)
  end

  def show
    @evenement = Evenement.find(params[:id])
    @comments = Commentaire.where(evenement_id: @evenement.id)
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def newcomment
    # @evenement = Evenement.find(params[:id])
    @new = Commentaire.new
    @new.comment = params['comment']
    @new.evenement = Evenement.find(params[:id_en_cours])
    @new.user = current_user
    @new.save
    redirect_to event_show_path(params[:id_en_cours])
  end

  def delcomment
    @comment = Commentaire.find(params[:id_comment])
    @comment.destroy
    redirect_to event_show_path(params[:id_event])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  protect_from_forgery with: :null_session
  def index
  end

  def filter
    # @category = Category.find(params[:category_id])
    @events = Evenement.where("titre like ? and category_id = ?","%#{params[:search]}%", "#{params[:category_id]}")
    p @events
    render json: @events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/evenements_helper.rb
module EvenementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organisateurs_helper.rb
module OrganisateursHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_footer.html.erb
<!--================ start footer Area  =================-->	
<footer class="footer-area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">About Agency</h6>
                    <p>The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">Navigation Links</h6>
                    <div class="row">
                        <div class="col-4">
                            <ul class="list_style">
                                <li><a href="#">Home</a></li>
                                <li><a href="#">Feature</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Portfolio</a></li>
                            </ul>
                        </div>
                        <div class="col-4">
                            <ul class="list_style">
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>										
                    </div>							
                </div>
            </div>							
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">Newsletter</h6>
                    <p>For business professionals caught between high OEM price and mediocre print and graphic output, </p>		
                    <div id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn sub-btn"><span class="lnr lnr-location"></span></button>		
                            </div>									
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget instafeed">
                    <h6 class="footer_title">InstaFeed</h6>
                    <ul class="list_style instafeed d-flex flex-wrap">
                        <li><img src="image/instagram/Image-01.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-02.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-03.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-04.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-05.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-06.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-07.jpg" alt=""></li>
                        <li><img src="image/instagram/Image-08.jpg" alt=""></li>
                    </ul>
                </div>
            </div>						
        </div>
        <div class="border_line"></div>
        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>
<!--================ End footer Area  =================-->

app/views/layouts/_nav.html.erb
<!--================Header Area =================-->
<header class="header_area">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="<%= root_path %>"><img style="height: 70px" src="/image/Logo.png" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                <ul class="nav navbar-nav menu_nav">
                    <li class="nav-item"><a class="nav-link" href="<%= root_path %>">Accueil</a></li> 
                    <li class="nav-item"><a class="nav-link" href="">About us</a></li>
                    <li class="nav-item"><a class="nav-link" href="">Contact</a></li>
                    <%if user_signed_in? %>
                        <li class="nav-item">
                            <%= link_to "mes evenements", evenements_path, data: {turbolinks: false}, class: "nav-link"%>
                        </li>
                        <li class="nav-item">
                            <%= link_to "Nouveau evenement", new_evenement_path, data: {turbolinks: false}, class: "nav-link"%>
                        </li>
                    <%end%>
                </ul>
                <div class="form-inline my-2 ml-auto">
                    <%= link_to search_path, class: "genric-btn primary-border circle", style: "margin-right: 20px" do%>
                        Rechercher
                        &nbsp;<span class="lnr lnr-magnifier"></span>
                    <%end%>
                    <%if user_signed_in? %>
                    <%= link_to destroy_user_session_path, method: :delete, class: "genric-btn danger-border circle" do %>
                        Deconnexion
                        <span class="lnr lnr-arrow-right"></span>
                    <%end%>

                    <%else%>
                      <%= link_to new_user_session_path, class: "genric-btn info-border circle", style: "margin-right: 20px" do%>
                        Connexion
                        <span class="lnr lnr-arrow-right"></span>
                      <%end%>
                    <%end%>
                </div>
            </div> 
        </nav>
    </div>
</header>
<!--================Header Area =================-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evpromote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="icon" href="/image/favicon.png" type="image/png">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/vendors/linericon/style.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css">
    <link rel="stylesheet" href="/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="/vendors/owl-carousel/owl.carousel.min.css">
    <!-- main css -->
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">

    <style type="text/css">
      .map{ width:100%; height: 500px; }
    </style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="/js/jquery-3.2.1.min.js"></script>
  <script src="/js/popper.js"></script>
  <script src="/js/bootstrap.min.js"></script>
  <script src="/vendors/owl-carousel/owl.carousel.min.js"></script>
  <script src="/js/jquery.ajaxchimp.min.js"></script>
  <script src="/vendors/bootstrap-datepicker/bootstrap-datetimepicker.min.js"></script>
  <script src="/vendors/nice-select/js/jquery.nice-select.js"></script>
  <script src="/js/mail-script.js"></script>
  <script src="/js/stellar.js"></script>
  <script src="/vendors/lightbox/simpleLightbox.min.js"></script>
  <script src="/js/custom.js"></script>
</html>